text_score = 0.5
min_side_len = 30
max_side_len = 2000
min_height = 30
width_height_ratio = 8.0

[inference]
intra_threads = 2
inter_threads = 1
parallel_execution = false
enable_cpu_mem_arena = false
execution_provider = "cpu"

[pipeline]
use_det = true
use_cls = false
use_rec = true

[det]
model_path = "models/ch_PP-OCRv5_det_mobile.onnx"
limit_side_len = 736
limit_type = "Min"
mean = [0.5, 0.5, 0.5]
std = [0.5, 0.5, 0.5]
thresh = 0.3
box_thresh = 0.5
max_candidates = 1000
unclip_ratio = 1.6
min_size = 3

[rec]
model_path = "models/ch_PP-OCRv5_rec_mobile.onnx"
dict_path = "models/ppocrv5_dict.txt"
image_shape = [3, 48, 320]
batch_size = 6
